language: python
python:
  - "3.6"
script:
  - echo "tag is $TRAVIS_TAG"
  - sed -i "s/0.0.0/`echo $TRAVIS_TAG | cut -c 2-`/" setup.py
  - sed -i "s/0.0.0/`echo $TRAVIS_TAG | cut -c 2-`/" onnxsim/__init__.py
  - cat setup.py
deploy:
  skip_cleanup: true
  provider: pypi
  user: "daquexian"
  password: $PYPI_PASSWORD
  on:
    branch: master
    tags: true
